Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace herenciayrelacionesgui.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace herenciayrelacionesgui.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

Pages/Prestamos/AddPrestamo.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using herenciayrelacionesgui.Clases;
using herenciayrelacionesgui.Persistencia;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace herenciayrelacionesgui.Pages.Prestamos
{
	public class AddPrestamosModel : PageModel
    {
        public List<Vehiculo> VehiculosDisponibles = new List<Vehiculo>();
        public void OnGet()
        {
            VehiculosDisponibles = PVehiculo.GetVehiculosDisponibles();
        }

        public async Task<IActionResult> OnGetConseguirCalculoPrecioAsync(string matricula)
        {
            // Obtener el vehículo correspondiente a la matrícula
            Vehiculo V = PVehiculo.GetVehiculo(matricula);

            // Calcular el precio del préstamo
            double precioPrestamo = V.calcularPrestamo();

            // Devolver el precio del préstamo como texto plano
            return Content(precioPrestamo.ToString());
        }

        public IActionResult OnPostAddPrestamo()
        {
            Console.WriteLine(Request.Form["vehiculos"].ToString());
            Prestamo p = new Prestamo(Convert.ToDateTime(Request.Form["fecha"]), PVehiculo.GetVehiculo(Request.Form["vehiculos"].ToString()), Convert.ToDouble(Request.Form["precio"]), Request.Form["cedulacliente"].ToString(), Convert.ToInt32(Request.Form["celularcliente"]));
            PPrestamo.AddPrestamo(p);
            return Redirect("./ListPrestamos");
        }

    }
}

Pages/Prestamos/ListPrestamos.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using herenciayrelacionesgui.Clases;
using herenciayrelacionesgui.Persistencia;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace herenciayrelacionesgui.Pages.Prestamos
{
	public class ListPrestamosModel : PageModel
    {
        public List<Prestamo> prestamos;
        public void OnGet()
        {
            this.prestamos = PPrestamo.GetPrestamos();
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace herenciayrelacionesgui.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

Pages/Vehiculos/AddVehiculo.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using herenciayrelacionesgui.Clases;
using herenciayrelacionesgui.Persistencia;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace herenciayrelacionesgui.Pages.Vehiculos
{
	public class AddVehiculoModel : PageModel
    {
        public void OnGet()
        {
        }

        public IActionResult OnPostAddVehiculo()
        {
            Vehiculo v;
            if (Request.Form["tipo_vehiculo"] == "automovil")
            {
                v = new Automovil(Request.Form["matricula"], Convert.ToDouble(Request.Form["preciomercado"]), true);
            }
            else
            {
                v = new Motocicleta(Request.Form["matricula"], Convert.ToDouble(Request.Form["preciomercado"]), true);
            }

            PVehiculo.AddVehiculo(v);
            return Redirect("/Vehiculos/ListVehiculos");
        }
    }
}

Pages/Vehiculos/ListVehiculos.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using herenciayrelacionesgui.Clases;
using herenciayrelacionesgui.Persistencia;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace herenciayrelacionesgui.Pages.Vehiculos
{
	public class ListVehiculosModel : PageModel
    {
        public List<Vehiculo> vehiculos;
        public void OnGet()
        {
            vehiculos = PVehiculo.GetVehiculos();
        }

        public IActionResult OnPostDeleteVehiculo()
        {
            PVehiculo.DeleteVehiculo(Request.Form["matricula"]);
            return Redirect("./ListVehiculos");
        }
    }
}

Pages/Vehiculos/UpdateVehiculo.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using herenciayrelacionesgui.Clases;
using herenciayrelacionesgui.Persistencia;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace herenciayrelacionesgui.Pages.Vehiculos
{
	public class UpdateVehiculoModel : PageModel
    {
        public Vehiculo v;
        public void OnGet(string matricula)
        {
            v = PVehiculo.GetVehiculo(matricula);
        }

        public IActionResult OnPostUpdateVehiculo() {

            if (Request.Form["tipo_vehiculo"] == "automovil")
            {
                v = new Automovil(Request.Form["matricula"], Convert.ToDouble(Request.Form["preciomercado"]), true);
            }
            else
            {
                v = new Motocicleta(Request.Form["matricula"], Convert.ToDouble(Request.Form["preciomercado"]), true);
            }

            PVehiculo.UpdateVehiculo(v);
            return Redirect("/Vehiculos/ListVehiculos");
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pages/Prestamos/AddPrestamo.cshtml
@page
@model herenciayrelacionesgui.Pages.Prestamos.AddPrestamosModel
@{

}

<div class="text-center">
    <h1 class="display-4" style="font-size: 40px">Agregar prestamo</h1>
    <form method="post">
        <div class="form-group">
            <label for="fecha">Fecha:</label>
            <input type="date" class="form-control" id="fecha" name="fecha">
        </div>
        <div class="form-group">
            <label for="vehiculos">Vehículos:</label>
            <select class="form-control" id="vehiculos" name="vehiculos" onchange="seleccionarVehiculo()">
                @foreach (var vehiculo in Model.VehiculosDisponibles)
                {
                    <option value="@vehiculo.Matricula">@vehiculo.Matricula $@vehiculo.PrecioMercado</option>
                }
            </select>
        </div>
        <div class="form-group">
            <label for="precio">Precio:</label>
            <input type="text" class="form-control" readonly id="precio" name="precio">
        </div>
        <div class="form-group">
            <label for="ci">Cédula cliente:</label>
            <input type="text" class="form-control" id="cedulacliente" name="cedulacliente">
        </div>
        <div class="form-group">
            <label for="ci">Celular cliente:</label>
            <input type="text" class="form-control" id="celularcliente" name="celularcliente">
        </div>
        <button type="submit" class="btn btn-primary" asp-page-handler="AddPrestamo">Agregar prestamo</button>
    </form>

</div>

<script>
    function seleccionarVehiculo() {
        var matriculaSeleccionada = document.getElementById("vehiculos").value;

        $.ajax({
            url: "?handler=ConseguirCalculoPrecio&matricula="+matriculaSeleccionada,
            method: "GET",
            success: function (response) {
                // Manejar la respuesta del servidor si es necesario
                document.getElementById("precio").value = response;
                console.log(response);
            },
            error: function (xhr, status, error) {
                // Manejar errores si es necesario
                console.error("Error en la solicitud AJAX:", error);
            }
        });
    }
</script>

Pages/Prestamos/ListPrestamos.cshtml
@page
@model herenciayrelacionesgui.Pages.Prestamos.ListPrestamosModel
@{
}

<div class="text-center">
    <h1 class="display-4">Lista de Prestamos</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Fecha</th>
                <th>Vehiculo</th>
                <th>Precio</th>
                <th>Cedula cliente</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var p in Model.prestamos)
            {
                <tr>
                    <td>@p.Fecha</td>
                    <td>@p.Vehiculo.ToString()</td>
                    <td>@p.Precio</td>
                    <td>@p.CedulaCliente</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - herenciayrelacionesgui</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/herenciayrelacionesgui.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">herenciayrelacionesgui</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Vehiculos/AddVehiculo">Agregar Vehiculos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Vehiculos/ListVehiculos">Listar Vehiculos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Prestamos/AddPrestamo">Agregar Prestamo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Prestamos/ListPrestamos">Listar Prestamos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - herenciayrelacionesgui - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Pages/Vehiculos/AddVehiculo.cshtml
@page
@model herenciayrelacionesgui.Pages.Vehiculos.AddVehiculoModel
@{
}

<div class="text-center">
    <h1 class="display-4" style="font-size: 40px">Agregar vehículo</h1>
    <form method="post">
        <div class="form-group">
            <label for="matricula">Matricula:</label>
            <input type="text" class="form-control" id="matricula" name="matricula">
        </div>
        <div class="form-group">
            <label for="preciomercado">Precio mercado:</label>
            <input type="text" class="form-control" id="preciomercado" name="preciomercado">
        </div>
        <div class="form-group">
            <label>
                <input type="radio" checked name="tipo_vehiculo" value="automovil">
                Automovil
            </label>
            <label>
                <input type="radio" name="tipo_vehiculo" value="motocicleta">
                Motocicleta
            </label>
        </div>
        <button type="submit" class="btn btn-primary" asp-page-handler="AddVehiculo">Agregar Vehiculo</button>
    </form>

</div>

Pages/Vehiculos/ListVehiculos.cshtml
@page
@model herenciayrelacionesgui.Pages.Vehiculos.ListVehiculosModel
@{
}

<div class="text-center">
    <h1 class="display-4">Lista de Vehiculos</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Matricula</th>
                <th>Precio mercado</th>
                <th>Disponible</th>
                <th>Tipo</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var v in Model.vehiculos)
            {
                <tr>
                    <td>@v.Matricula</td>
                    <td>@v.PrecioMercado</td>
                    <td>@v.Disponible</td>
                    <td>@v.GetType().Name</td>
                    <td>
                        <a class="btn btn-primary" asp-page="./UpdateVehiculo" asp-route-matricula="@v.Matricula">Editar</a>
                        <form method="post" asp-page-handler="DeleteVehiculo">
                            <input type="hidden" name="matricula" value="@v.Matricula" />
                            <button type="submit" class="btn btn-danger">Eliminar</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Pages/Vehiculos/UpdateVehiculo.cshtml
@page
@model herenciayrelacionesgui.Pages.Vehiculos.UpdateVehiculoModel
@{
}


<div class="text-center">
    <h1 class="display-4" style="font-size: 40px">Modificar vehículo</h1>
    <form method="post">
        <div class="form-group">
            <label for="matricula">Matricula:</label>
            <input type="text" class="form-control" id="matricula" readonly value="@Model.v.Matricula" name="matricula">
        </div>
        <div class="form-group">
            <label for="preciomercado">Precio mercado:</label>
            <input type="text" class="form-control" id="preciomercado" value="@Model.v.PrecioMercado" name="preciomercado">
        </div>
        <div class="form-group">
            <label>
                <input type="radio" name="tipo_vehiculo" value="automovil" @(Model.v.GetType().Name.Equals("Automovil") ? "checked" : "")>
                Automovil
            </label>
            <label>
                <input type="radio" name="tipo_vehiculo" value="motocicleta" @(Model.v.GetType().Name.Equals("Motocicleta") ? "checked" : "")>
                Motocicleta
            </label>
        </div>
        <button type="submit" class="btn btn-primary" asp-page-handler="UpdateVehiculo">Modificar Vehiculo</button>
    </form>

</div>